# To create an environment with all the libraries needed move the
# anaconda command prompt (or equivalent) to this directory and type
#
# conda env create --file conda_env_experimental_physics.yml
# 
name: experimental_methods
channels:
    - conda-forge
    - anaconda
dependencies:
    - python>=3.8.1
    - numpy>=1.18.1
    - scipy>=1.4.1
    - matplotlib>=3.1.3
    - pandas>=1.0.0
    - xlrd>=1.2.0
    - plotly>=4.5.0
    - seaborn>=0.9.0
    - scikit-learn>=0.22.1
    - jupyter>=1.0.0
    - jupyterlab>=1.2.6
    - jupyter_contrib_nbextensions>=0.5.1
    - rise>=5.6.0
    - pip
    - nbconvert

    - pip:
    # works for regular pip packages
       - wolframclient # https://blog.wolfram.com/2019/05/16/announcing-the-wolfram-client-library-for-python/
