# conda env create --file DataMining.yml
name: experimental_physics
channels:
    - conda-forge
    - anaconda
dependencies:
    - python=3.8.1
    - numpy=1.18.1
    - scipy=1.4.1
    - matplotlib=3.1.3
    - pandas=1.0.0
    - xlrd=1.2.0
    - plotly=4.5.0
    - seaborn=0.9.0
    - scikit-learn=0.22.1
    - jupyter=1.0.0
    - jupyterlab=1.2.6
    - jupyter_contrib_nbextensions=0.5.1
    - rise=5.6.0
    - pip
    - wolframclient
